### ISSUE TITLE
Does not respond on slack adapter

### ISSUE THREAD

**Issue by dankeller** [jeffbyrnes/hubot-forecast#18] opened 2017-04-25 15:53 UTC
During testing, using the shell, forecast seem to work fine and responds with current forecast. When running hubot with the Slack adapter, I see the following message in the terminal, but nothing appears in Slack:

`[Forecast] Requesting forecast data: https://api.forecast.io/forecast/[...]`

**Comment by jeffbyrnes** [comment] 2017-04-25 15:56
@dankeller thanks for your interest! That would be the expected behavior:

* You can make forecast requests
* The bot sits, polling Dark Sky for inclement weather

However, the code is a total mess, and has some glaring bugs (see #3 for one example). I’ve been meaning to come back to it & refactor it completely, but have yet to do so.

Have you had any inclement weather since starting up your Hubot w/ `hubot-forecast` installed & configured?

**Comment by dankeller** [comment] 2017-04-25 18:36
Thanks for responding!

No inclement weather has been posted to slack since I setup `hubot-forecast` (2 months). We have definitely had rain, wind, etc in that time.

Nothing in the stdout but a lot of `[Forecast] Sleeping` but my logs only go back a few days.

**Comment by jeffbyrnes** [comment] 2017-04-25 18:51
@dankeller damn; sounds like `hubot-forecast` is well & truly broken as of now.

Sadly, I am not sure I will have any time to devote to it anytime soon. How’s your JavaScript? 😃

**Comment by jeffbyrnes** [comment] 2017-10-17 15:40
@dankeller I’m going to go ahead & close this. Please follow #15 if you want to know when I (maybe) get back to working on this.

We’re in the midst some bigger projects, so this has fallen far by the wayside.

**Closed as completed by jeffbyrnes** 2017-10-17 15:40 UTC
Labels: question
